# Generated by Django 5.2.2 on 2025-07-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_remove_listing_image_listing_image_main_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='label',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='listing_type',
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('araba', 'Araba'), ('ev', 'Ev'), ('arsa', 'Arsa')], default='ev', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='type',
            field=models.CharField(choices=[('Satılık', 'Satılık'), ('Kiralık', 'Kiralık')], default='ev', max_length=10),
            preserve_default=False,
        ),
    ]
