# Generated by Django 5.2.2 on 2025-07-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_remove_listing_label_remove_listing_listing_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='longitude',
        ),
        migrations.AddField(
            model_name='listing',
            name='coordinates',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
