# Generated by Django 5.2.2 on 2025-07-23 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_remove_listing_latitude_remove_listing_longitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='image_main',
            new_name='image',
        ),
    ]
