# Generated by Django 5.2.2 on 2025-07-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('araba', 'Araba'), ('ev', 'Ev'), ('arsa', 'Arsa')], max_length=10)),
                ('type', models.CharField(choices=[('Satılık', 'Satılık'), ('Kiralık', 'Kiralık')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('images', models.JSONField(blank=True, null=True)),
                ('coordinates', models.JSONField(blank=True, null=True)),
                ('specs', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
